// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/goadesign/goa-cellar/design
// --out=$(GOPATH)/src/github.com/goadesign/goa-cellar
// --version=v1.1.0
//
// API "cellar": public TestHelpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package test
