// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cellar": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/goadesign/goa-cellar/design
// --out=$(GOPATH)/src/github.com/goadesign/goa-cellar
// --version=v1.3.0

package test
